name: Main

on:
  push:
    branches: [master-dev]
  pull_request:
    branches: [master-dev]
  workflow_dispatch:

jobs:
  BuildAndroid:
    name: Android
    permissions: write-all
    runs-on: macos-15
    uses: ./.github/workflows/build.yml
    with:
      name: Android
      os: macos-15
      buildArgs: "android"
      setupScript: sh ./setup/mobile.sh
      exportPath: android
      artifactName: P-Slice.1.0.android
      artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
